openapi: 3.0.0
info:
    title: Chatty
    version: 1.0.0
paths:
    /api/users/signup:
        post:
            summary: Signup
            description: Register a new user.
            tags:
                - Users
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                userName:
                                    type: string
                                email:
                                    type: string
                                password:
                                    type: string
                            example:
                                userName: JohnDoe
                                email: john.doe@example.com
                                password: password123
                                passwordConfirmation: password123
            responses:
                "201":
                    description: User signed up successfully
                "422":
                    description: Validation error
